// Healthcare advertising policy rules database

import type { PolicyRule } from "../types";

export const POLICY_RULES: PolicyRule[] = [
  // ============================================
  // PROHIBITED CLAIMS
  // ============================================
  {
    id: "PC001",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "critical",
    keywords: ["cure", "cures", "cured", "curing"],
    description: "Claims of curing diseases or conditions are prohibited without FDA approval",
    policyReference: "Policy 4.1 – No Cure Claims",
    suggestedAlternative: "Consider using 'may help manage' or 'supports treatment of'",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC002",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "critical",
    keywords: ["miracle", "miraculous", "magic", "magical"],
    description: "Exaggerated or miracle claims are strictly prohibited",
    policyReference: "Policy 4.2 – No Miracle Claims",
    suggestedAlternative: "Use evidence-based language like 'clinically tested' or 'shown to help'",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC003",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "critical",
    keywords: ["guaranteed results", "guarantee results", "100% guaranteed", "money-back guarantee on results"],
    description: "Guaranteeing specific health outcomes is prohibited",
    policyReference: "Policy 4.3 – No Guaranteed Results",
    suggestedAlternative: "Replace with 'individual results may vary' or 'satisfaction guarantee'",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC004",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "critical",
    keywords: ["FDA-approved", "FDA approved", "approved by FDA"],
    pattern: "FDA[- ]?approved",
    description: "FDA approval claims require documented proof and proper context",
    policyReference: "Policy 4.4 – FDA Approval Claims",
    suggestedAlternative: "If not FDA-approved, remove claim. If approved, include approval documentation reference",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC005",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "critical",
    keywords: ["instant results", "immediate results", "overnight results", "works instantly"],
    description: "Claims of instant or immediate health results are misleading",
    policyReference: "Policy 4.5 – No Instant Result Claims",
    suggestedAlternative: "Use realistic timeframes like 'results typically seen within X weeks'",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC006",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "warning",
    keywords: ["doctor recommended", "doctor approved", "doctors recommend", "physicians recommend"],
    description: "Medical endorsement claims require proper documentation",
    policyReference: "Policy 4.6 – Medical Endorsement Claims",
    suggestedAlternative: "If verified, cite specific study or doctor name with permission",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC007",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "critical",
    keywords: ["no side effects", "zero side effects", "side effect free", "completely safe"],
    description: "Claims of zero side effects are typically unsubstantiated and misleading",
    policyReference: "Policy 4.7 – Side Effect Claims",
    suggestedAlternative: "Use 'generally well-tolerated' or list known side effects",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC008",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "warning",
    keywords: ["clinically proven", "scientifically proven", "proven to work"],
    description: "Proven claims require citation of peer-reviewed studies",
    policyReference: "Policy 4.8 – Proof Claims",
    suggestedAlternative: "Use 'clinically studied' or cite specific research with reference",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "PC009",
    category: "Prohibited Claims",
    type: "prohibited_claim",
    severity: "critical",
    keywords: ["permanent results", "permanent solution", "forever", "never again"],
    description: "Claims of permanent health outcomes are typically misleading",
    policyReference: "Policy 4.9 – Permanent Result Claims",
    suggestedAlternative: "Use 'long-lasting' or specify realistic duration with continued use",
    platforms: "all",
    productCategories: "all",
  },

  // ============================================
  // REQUIRED DISCLAIMERS
  // ============================================
  {
    id: "RD001",
    category: "Required Disclaimers",
    type: "required_disclaimer",
    severity: "critical",
    keywords: ["consult your doctor", "consult a doctor", "consult physician", "speak with your doctor"],
    description: "Healthcare products must include medical consultation advisory",
    policyReference: "Policy 5.1 – Medical Consultation Disclaimer",
    suggestedAlternative: "Add: 'Consult your healthcare provider before starting any new treatment'",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "RD002",
    category: "Required Disclaimers",
    type: "required_disclaimer",
    severity: "critical",
    keywords: ["results may vary", "individual results may vary", "results vary"],
    description: "Variable results disclaimer is required for health outcome claims",
    policyReference: "Policy 5.2 – Results Variation Disclaimer",
    suggestedAlternative: "Add: 'Individual results may vary'",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "RD003",
    category: "Required Disclaimers",
    type: "required_disclaimer",
    severity: "critical",
    keywords: ["prescription required", "Rx required", "requires prescription", "prescription only"],
    description: "Prescription medications must clearly state Rx requirement",
    policyReference: "Policy 5.3 – Prescription Requirement Disclaimer",
    suggestedAlternative: "Add: 'Prescription required. Subject to physician approval.'",
    platforms: "all",
    productCategories: ["erectile_dysfunction", "weight_loss", "mental_health"],
  },
  {
    id: "RD004",
    category: "Required Disclaimers",
    type: "required_disclaimer",
    severity: "warning",
    keywords: ["not intended to diagnose", "not intended to treat", "dietary supplement"],
    description: "Supplements require FDA disclaimer about not treating diseases",
    policyReference: "Policy 5.4 – Supplement Disclaimer",
    suggestedAlternative: "Add: 'These statements have not been evaluated by the FDA. This product is not intended to diagnose, treat, cure, or prevent any disease.'",
    platforms: "all",
    productCategories: ["supplements", "weight_loss", "hair_loss"],
  },

  // ============================================
  // PLATFORM-SPECIFIC RULES - META
  // ============================================
  {
    id: "META001",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "critical",
    keywords: ["before and after", "before/after", "transformation photo"],
    description: "Meta prohibits before-and-after imagery in health/weight loss ads",
    policyReference: "Meta Policy 13.4 – Personal Health Imagery",
    suggestedAlternative: "Use lifestyle imagery or product shots instead of transformation photos",
    platforms: ["meta"],
    productCategories: ["weight_loss", "skincare", "hair_loss"],
  },
  {
    id: "META002",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "critical",
    keywords: ["lose weight fast", "rapid weight loss", "lose X pounds", "shed pounds"],
    description: "Meta restricts specific weight loss quantity claims",
    policyReference: "Meta Policy 13.5 – Weight Loss Claims",
    suggestedAlternative: "Focus on healthy lifestyle rather than specific weight targets",
    platforms: ["meta"],
    productCategories: ["weight_loss"],
  },
  {
    id: "META003",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "warning",
    keywords: ["you", "your body", "your weight", "your skin"],
    pattern: "\\b(you|your)\\b.*\\b(body|weight|skin|hair|face)\\b",
    description: "Meta restricts personal attribute targeting in health ads",
    policyReference: "Meta Policy 13.6 – Personal Attributes",
    suggestedAlternative: "Use third-person language: 'People who...' instead of 'You...'",
    platforms: ["meta"],
    productCategories: "all",
  },
  {
    id: "META004",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "critical",
    keywords: ["erectile dysfunction", "ED treatment", "impotence", "sexual dysfunction"],
    description: "Meta has strict restrictions on sexual health advertising",
    policyReference: "Meta Policy 13.8 – Adult Health Products",
    suggestedAlternative: "Use euphemistic language and ensure age-gating is in place",
    platforms: ["meta"],
    productCategories: ["erectile_dysfunction"],
  },

  // ============================================
  // PLATFORM-SPECIFIC RULES - GOOGLE
  // ============================================
  {
    id: "GOOG001",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "critical",
    keywords: ["prescription drugs", "controlled substances", "opioids", "schedule"],
    description: "Google requires pharmacy certification for prescription drug ads",
    policyReference: "Google Healthcare Policy 4.2 – Prescription Drugs",
    suggestedAlternative: "Ensure proper certification is obtained before advertising Rx products",
    platforms: ["google"],
    productCategories: "all",
  },
  {
    id: "GOOG002",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "warning",
    keywords: ["weight loss supplement", "diet pill", "fat burner"],
    description: "Google restricts certain weight loss supplement advertising",
    policyReference: "Google Healthcare Policy 4.5 – Weight Loss Products",
    suggestedAlternative: "Focus on lifestyle and wellness rather than supplement-specific claims",
    platforms: ["google"],
    productCategories: ["weight_loss", "supplements"],
  },

  // ============================================
  // PLATFORM-SPECIFIC RULES - TIKTOK
  // ============================================
  {
    id: "TIKTOK001",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "critical",
    keywords: ["challenge", "trend", "viral"],
    description: "TikTok prohibits health challenges that could encourage dangerous behavior",
    policyReference: "TikTok Community Guidelines 8.2 – Dangerous Challenges",
    suggestedAlternative: "Avoid framing health products as challenges or trends",
    platforms: ["tiktok"],
    productCategories: "all",
  },
  {
    id: "TIKTOK002",
    category: "Platform Restrictions",
    type: "platform_specific",
    severity: "warning",
    keywords: ["detox", "cleanse", "purify your body"],
    description: "TikTok scrutinizes detox/cleanse claims heavily",
    policyReference: "TikTok Ad Policy 6.4 – Health Claims",
    suggestedAlternative: "Use 'supports digestive health' instead of detox claims",
    platforms: ["tiktok"],
    productCategories: ["weight_loss", "supplements"],
  },

  // ============================================
  // RESTRICTED IMAGERY
  // ============================================
  {
    id: "IMG001",
    category: "Restricted Imagery",
    type: "restricted_imagery",
    severity: "critical",
    description: "Before-and-after comparison images are restricted on most platforms",
    policyReference: "Policy 6.1 – Before/After Imagery",
    suggestedAlternative: "Use lifestyle photos showing healthy, active individuals",
    platforms: "all",
    productCategories: ["weight_loss", "skincare", "hair_loss"],
  },
  {
    id: "IMG002",
    category: "Restricted Imagery",
    type: "restricted_imagery",
    severity: "critical",
    description: "Images depicting negative body image or body shaming are prohibited",
    policyReference: "Policy 6.2 – Body Image Standards",
    suggestedAlternative: "Use positive, empowering imagery that celebrates diversity",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "IMG003",
    category: "Restricted Imagery",
    type: "restricted_imagery",
    severity: "critical",
    description: "Nudity or sexually suggestive imagery is prohibited in healthcare ads",
    policyReference: "Policy 6.3 – Appropriate Imagery",
    suggestedAlternative: "Use tasteful, clothed lifestyle imagery",
    platforms: "all",
    productCategories: "all",
  },
  {
    id: "IMG004",
    category: "Restricted Imagery",
    type: "restricted_imagery",
    severity: "warning",
    description: "Medical procedure imagery should be used cautiously",
    policyReference: "Policy 6.4 – Medical Imagery",
    suggestedAlternative: "Use illustrations or diagrams instead of graphic medical photos",
    platforms: "all",
    productCategories: "all",
  },
];

export const PLATFORM_DISPLAY_NAMES: Record<string, string> = {
  meta: "Meta (Facebook/Instagram)",
  google: "Google Ads",
  tiktok: "TikTok",
};

export const PRODUCT_CATEGORY_DISPLAY_NAMES: Record<string, string> = {
  erectile_dysfunction: "Erectile Dysfunction (ED)",
  hair_loss: "Hair Loss Treatment",
  weight_loss: "Weight Loss",
  skincare: "Skincare",
  supplements: "Dietary Supplements",
  mental_health: "Mental Health",
  other: "Other Healthcare",
};

export const SEVERITY_CONFIG = {
  critical: {
    label: "Critical",
    color: "red",
    weight: 25, // Points deducted from score
  },
  warning: {
    label: "Warning",
    color: "yellow",
    weight: 10,
  },
  info: {
    label: "Info",
    color: "blue",
    weight: 5,
  },
};

